name: Build Canet de notre APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer les dépendances système
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev cmake \
            libffi-dev libssl-dev automake autopoint gettext

      - name: Installer Buildozer
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install buildozer "Cython==0.29.37"

      - name: Compiler l'APK
        run: |
          yes | buildozer -v android debug

      - name: Publier l'APK
        uses: actions/upload-artifact@v4
        with:
          name: canet-de-notre-apk
          path: bin/*.apk
          if-no-files-found: error
